# Generated by Django 5.0.2 on 2024-11-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0002_dividend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dividend",
            name="investment",
        ),
    ]
