# Generated by Django 5.0.2 on 2024-11-11 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0003_remove_dividend_investment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
